export const ADD_TO_CARD = "ADD_TO_CARD"
export const REMOVE_TO_CARD = "REMOVE_TO_CARD"
export const UPDATE_SIZE_COLOR = "UPDATE_SIZE_COLOR"
export const RESET_CARD = "RESET_CARD"

export const ADD_TO_CARD_FAVOR = "ADD_TO_CARD_FAVOR"
export const REMOVE_TO_CARD_FAVOR = "REMOVE_TO_CARD_FAVOR"
export const DELETE_FAVOR = "DELETE_FAVOR"